version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    image: pythonproject1:latest
    build: .
    command: sh -c "sleep 5 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/events
      - DATABASE_URL_SYNC=postgresql://postgres:postgres@db:5432/events
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker:
    image: pythonproject1:latest  # shared image
    container_name: queue-worker
    command: sh -c "python scripts/queue_worker.py"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL_SYNC=postgresql://postgres:postgres@db:5432/events
      - REDIS_URL=redis://redis:6379/0
      - USE_QUEUE=true
    volumes:
      - .:/app

volumes:
  postgres_data:
